version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:5.6.8
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      tweet_analysis_net:

  listener:
    build:
      context: ./listener
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    env_file:
      - config.env
    networks:
      tweet_analysis_net:
    command: ["/opt/listener/wait-for.sh", "elasticsearch:9200", "-t", "60", "--", 
              "python3", "/opt/listener/main.py"]

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:5.6.8
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      tweet_analysis_net:

volumes:
  es_data:

networks:
  tweet_analysis_net:
